[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[context.production.environment]
  ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200